# https://leetcode.com/problems/sliding-window-maximum/
from collections import deque
def maxSlidingWindow(nums, k):
    deq = deque()
    res = []
    for i in range(len(nums)):
        if deq and deq[0] < i -k +1:
            deq.popleft()
        while deq and nums[deq[-1]] < nums[i]:
            deq.pop()
        deq.append(i)
        if i >= k- 1:
            res.append(nums[deq[0]])
    return res

nums = [1,3,-1,-3,5,3,6,7]
print(maxSlidingWindow(nums, 3))

"""
AMENIC HESHT BAYC DANDAX TARBERAKY 3 ANGAM CYCLE FRALOV ANELN E
BAYC AYD DEPQUM MI QANI ANGAM NUYN HASHVARKY ANELU ENQ
VORPESZI MAX GTNELU XNDIRY OPYIMIZACNENQ KAROX ENQ PAHEL DEQUE
AYSINQN VERCNUM ENQ DEQUEUE EV NRA MEJ PAHUM MAX ELEMENTNERY YST NVAZMAN
MER NPATAKN E DEQUE I FRONT UM PAHEL MECAGUYN ELEMENTY
AMEN ELEMENTI HAMAR STUGUM ENQ ARDYOQ AYD DEQUE I ARAJIN(FRONT) ELEMENTY
GTNVUM E WINDOW I MEJ TE DURS E
ORINAK [1,-1,0,4] I DEPQUM ERB NAYENQ [-1,0,4] WINDOW N
1 Y ARDEN AYD WINDOW I MEJ CHI LINI (K=3)
AYSINQN ETE IDX = 3 APA DEQUE[0] RD ELEMENTY AYSINQN 0 N(PAHELU ENQ IDX NERY)
POQR E QAN I - K + 1 AYSINQN AYN KETY VORY MER WINDOW I SKIZBN E
EV ETE NOR GTAC ELEMENTY AVELI MEC E QAN VERJUM UM GTNVOXY APA AYN KAROX ENQ JNJEL
AYNQAN JMNK QANI DER AVELI MEC CHENQ GTEL
ETE K CHAPANI WINDOW GTEL ENQ ARDEN KAROX ENQ VERCNEL DEQUE I FRONT Y EV GCEL RESULT I MEJ

DEQUEUE I MITQY KAYANUM E NRANUM VOR PAHENQ ELEMENTNERY YST NVAZMAN EV AMEN WINDOW I HAMAR 
IR MAXIMUM Y, EV HAMEMATUM ENQ DEQUEUE I VERJIN ELEMENETNERI HET QANI VOR
MEZ HAMAR KAREVOR E VOR MISHT DEQUEUE I ARAJIN Y LINI MECAGUYN EV MISHT NVAZMAN KARGOV
EV MYS KOXMIC VERJIC ENQ STUGUM QNAI VOR ETE AYD ELEMENTENRY POQR EN
APA ANIMAST E NRANC PAHELY
"""
