# https://leetcode.com/problems/trapping-rain-water/
### FULLY DONE ###
def trapping_rain_water(heights):
    lft, rgt = 0, len(heights) - 1
    l_max, r_max = 0, 0
    result = 0
    while lft <= rgt:
        if l_max < r_max:
            l_max = max(l_max, heights[lft])
            result += l_max - heights[lft]
            lft += 1
        else:
            r_max = max(r_max, heights[rgt])
            result += r_max - heights[rgt]
            rgt -= 1
    return result


print(trapping_rain_water([0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]))

"""
VERCNUM ENQ 2 POINTER EV OPTIMIZACNUM ENQ CLASSIC LUCUMY
AYSINQN CLASSIC Y ASUM E VOR MENQ KAROX ENQ VERCNEL BOLOR I RD KETERY
EV DRANC HAMAR HASHVEL DZAX EV AJ MAX RY U DRANC MINI CHAPOV - HENC
IRENC BARDZRUCTYUN I CHAPOV JUR KGTNVI HENC AYD BARDZRUTYAN
BAYC AYS TARBERAKOV MENQ MI QANI ANGAM HASHVUM ENQ NUYN MAX RY
VORY OPTIMAL CHE
DRA HAMAR DYNAMYC KARELI E HASHVEL AYN
ETE DZAX DZOXY POQR E AJINIC UREMN DZAX - HENC IR BARCRUTYAN CHAPOV JUR KARELI E PAHEL
NUYNY HAKARAKI HAMAR
BAYC AMEN QAYLI HAMAR MINCHEV JRI CHAPY HASHVELY PETQ E HASHVENQ DZAX EV AJ MAX RRY
QANI VOR KAROX E HENC AYD KETN E IR HAMAR AMENABARDZRY VOCH TE NRANIC DZAX KAM AJ GTNVOXY
AYSINQN VERCNUM ENQ 2 POINTER
MINCHEV NRANC HATVELY SKSUM PTTVEL YNDUNELOV VOR DZAX EV AJ AMENAMECNERY 0 EN
EV AMEN KETUM VERAHASHVARK ANEL U PAHEL MAX Y
MYUS KOXMIC LUCUM ENQ AYN XNDIRY VOR ETE LEFT Y POQR E RIGHT IC MENQ ARAJ ENQ TALIS 
AYN VOR GTNENQ AVELI BARDZR LEFT OV 
"""